spring:
    datasource:
        url: jdbc:h2:mem:taxdb
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    application:
        name: spring-data-jpa
    security:
        oauth2:
            client:
                registration: 
                    google: 
                        clientId: # Insert client id
                        clientSecret: # Insert client secret
